# 1. Base Image
FROM ubuntu:latest

# 2. Update APT Packages
RUN apt-get update

# 3. Upgrade Already Installed Packages
RUN apt-get upgrade -y

# 4. Display "Hello World!" when the container starts
CMD echo "Hello World!"
